[package]
name = "monetproxy"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
argsplitter = "0.4.0"
box_drawing = "0.1.2"
